apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: codelens
data:
  GROQ_MODEL: "llama3-8b-8192"
  CHROMA_HOST: "chromadb"
  CHROMA_PORT: "8000"
  CHROMA_PERSIST_DIR: "/app/data/chromadb"
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"
  LOG_LEVEL: "INFO"
  FRONTEND_URL: "http://frontend:3000"
  BACKEND_PORT: "8000"
