apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: codelens
spec:
  selector:
    app: codelens
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
