apiVersion: v1
kind: Service
metadata:
  name: chromadb
  namespace: stacksense
spec:
  selector:
    app: stacksense
    component: chromadb
  ports:
    - port: 8000
      targetPort: 8000
  clusterIP: None
