apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: codelens
spec:
  selector:
    app: codelens
    component: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
