"""
CodeLens Code Chunker (app/utils/chunker.py)

Splits code files into semantically meaningful chunks, then wraps each
chunk in a context header so the embedding model can answer questions like
"what does embedding_service.py do?" by connecting the query to the right file.

Three chunking strategies:
  - Python    → AST-based (one chunk per function / class / module-level block)
  - JS / TS   → Regex-based (one chunk per exported function / class)
  - All else  → Overlapping sliding window (60-line chunks, 10-line overlap)

Every chunk's document string starts with:
  File: <path>
  Language: <language>
  Function: <name>

  <code content>

This context header is critical — without it the embedding model cannot
connect "which file does X?" questions to the correct chunks in ChromaDB.
"""

import ast
import re
from typing import List, Optional

from groq import Groq
from langchain_text_splitters import RecursiveCharacterTextSplitter, Language

from app.config import get_settings
from app.utils.logger import get_logger

logger   = get_logger(__name__)
settings = get_settings()

# ── Sliding-window defaults (read from config — can be overridden in .env) —
# CHUNK_LINES       = settings.chunk_lines         (default: 60)
# CHUNK_OVERLAP     = settings.chunk_overlap_lines  (default: 10)


# ── Groq description client (lazy singleton) ──────────────────────────

_groq_client: Optional[Groq] = None

def _get_groq_client() -> Optional[Groq]:
    """Return a lazy Groq client for description generation, or None if key missing."""
    global _groq_client
    if _groq_client is not None:
        return _groq_client
    key = getattr(settings, "groq_api_key", None)
    if not key:
        logger.warning("chunk_desc_skip  reason=no_groq_api_key")
        return None
    _groq_client = Groq(api_key=key)
    return _groq_client


def _generate_description(code: str, func_name: str, file_path: str) -> str:
    """
    Call Groq LLaMA3 to produce a one-line plain-English description of a code chunk.
    Falls back to an empty string silently if the API is unavailable or the chunk is too small.
    """
    # Skip tiny stubs — not worth an API call
    if len(code.strip()) < 40:
        return ""

    client = _get_groq_client()
    if client is None:
        return ""

    prompt = (
        f"In ONE concise sentence, describe what this code does. "
        f"Be specific: mention what it takes as input, what it returns, and its purpose.\n\n"
        f"File: {file_path}\n"
        f"Symbol: {func_name}\n\n"
        f"Code:\n{code[:1200]}\n\n"
        f"One sentence description:"
    )

    try:
        response = client.chat.completions.create(
            model=settings.groq_model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=60,
            temperature=0.0,
        )
        desc = response.choices[0].message.content.strip()
        # Strip any leading label the model might add ("Description: ...")
        for prefix in ("Description:", "One sentence description:", "Answer:"):
            if desc.lower().startswith(prefix.lower()):
                desc = desc[len(prefix):].strip()
        return desc
    except Exception as exc:
        logger.warning(f"chunk_desc_failed  func={func_name}  error={exc}")
        return ""


# ── Context header builder ─────────────────────────────────────────────

def _make_document(
    file_path: str,
    language: str,
    name: str,
    code_content: str,
    description: str = "",
) -> str:
    """
    Prepend the context header to raw code so the embedding model
    knows which file and which symbol this chunk belongs to.
    The optional description is a one-line plain-English summary
    generated by the LLM — this dramatically improves retrieval accuracy
    by bridging natural-language questions to raw code.
    """
    desc_line = f"Description: {description}\n" if description else ""
    return (
        f"File: {file_path}\n"
        f"Language: {language}\n"
        f"Function: {name}\n"
        f"{desc_line}\n"
        f"{code_content}"
    )


def _make_chunk(
    file_path: str,
    language: str,
    name: str,
    code_content: str,
    start_line: int,
    end_line: int,
    chunk_type: str,
    description: str = "",
) -> dict:
    """
    Build the canonical chunk dict used throughout the pipeline.

    Returns:
        {
          "document": "<context header>\n\n<code>",
          "metadata": { file_path, start_line, end_line, language,
                        chunk_type, chunk_name, description }
        }
    """
    return {
        "document": _make_document(file_path, language, name, code_content, description),
        "metadata": {
            "file_path":   file_path,
            "start_line":  start_line,
            "end_line":    end_line,
            "language":    language,
            "chunk_type":  chunk_type,
            "chunk_name":  name,
            "description": description,
        },
    }


# ── Python AST chunker ────────────────────────────────────────────────

def _chunk_python(content: str, file_path: str) -> List[dict]:
    """
    Chunk a Python file using its AST.

    Strategy:
    - Each top-level FunctionDef / AsyncFunctionDef → one chunk (type: function)
    - Each top-level ClassDef (including all its methods) → one chunk (type: class)
    - All remaining module-level statements → one "module-level" chunk (type: module)
    - Falls back to sliding-window if the file has a SyntaxError
    """
    try:
        tree = ast.parse(content)
    except SyntaxError as exc:
        logger.debug(f"Skipping AST for {file_path} — SyntaxError: {exc}")
        return _chunk_recursive_langchain(content, file_path, "python")

    lines      = content.splitlines()
    chunks: List[dict] = []
    covered_lines: set = set()

    # Only process TOP-LEVEL nodes (direct children of the Module)
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            continue

        start      = node.lineno          # 1-indexed
        end        = node.end_lineno      # 1-indexed
        name       = node.name
        chunk_type = "class" if isinstance(node, ast.ClassDef) else "function"
        code       = "\n".join(lines[start - 1 : end])

        if not code.strip():
            continue

        covered_lines.update(range(start, end + 1))
        desc = _generate_description(code, name, file_path)
        chunks.append(_make_chunk(file_path, "python", name, code, start, end, chunk_type, description=desc))
        logger.debug(f"chunk_ast_node  {chunk_type:<8} {name}  lines {start}-{end}  desc={'yes' if desc else 'no'}  file={file_path}")

    # Collect module-level code (imports, constants, etc.) that wasn't covered
    module_lines = [
        (i + 1, line)
        for i, line in enumerate(lines)
        if (i + 1) not in covered_lines
    ]
    if module_lines:
        module_code = "\n".join(l for _, l in module_lines)
        if module_code.strip():
            start_l = module_lines[0][0]
            end_l   = module_lines[-1][0]
            chunks.insert(0, _make_chunk(
                file_path, "python", "module-level",
                module_code, start_l, end_l, "module",
            ))
            logger.debug(f"chunk_ast_node  module   module-level  lines {start_l}-{end_l}  file={file_path}")

    if not chunks:
        logger.debug(f"No AST nodes found in {file_path}, falling back to recursive chunker")
        return _chunk_recursive_langchain(content, file_path, "python")

    return chunks


# ── Intelligent Recursive Chunker (Langchain) ─────────────────────────

LANGUAGE_MAP = {
    "javascript": Language.JS,
    "typescript": Language.TS,
    "java": Language.JAVA,
    "go": Language.GO,
    "rust": Language.RUST,
    "ruby": Language.RUBY,
    "php": Language.PHP,
    "c": Language.CPP,
    "cpp": Language.CPP,
    "csharp": Language.CSHARP,
    "swift": Language.SWIFT,
    "scala": Language.SCALA,
    "html": Language.HTML,
    "markdown": Language.MARKDOWN,
}

def _chunk_recursive_langchain(
    content: str,
    file_path: str,
    language: str,
    chunk_size: int | None = None,
    overlap: int | None = None,
) -> List[dict]:
    """
    Intelligent chunking using Langchain's language-aware recursive splitters.
    Preserves functions and structures across many languages, and falls back
    to clean sentence/paragraph splitting for unknown languages like JSON or CSS.
    """
    chunk_size = chunk_size if chunk_size is not None else settings.chunk_lines
    overlap    = overlap    if overlap    is not None else settings.chunk_overlap_lines

    # Langchain uses characters, our config is in lines. 
    # Average line of code is ~40 characters.
    char_chunk_size = chunk_size * 40
    char_overlap = overlap * 40

    lc_lang = LANGUAGE_MAP.get(language)
    if lc_lang:
        try:
            splitter = RecursiveCharacterTextSplitter.from_language(
                language=lc_lang,
                chunk_size=char_chunk_size,
                chunk_overlap=char_overlap,
                add_start_index=True,
            )
        except Exception as e:
            logger.warning(f"Failed to load language {lc_lang} splitter, using fallback: {e}")
            splitter = RecursiveCharacterTextSplitter(
                chunk_size=char_chunk_size,
                chunk_overlap=char_overlap,
                add_start_index=True,
            )
    else:
        # Fallback splits on \n\n, \n, and space
        splitter = RecursiveCharacterTextSplitter(
            chunk_size=char_chunk_size,
            chunk_overlap=char_overlap,
            add_start_index=True,
        )

    # Empty files might cause issues, check first
    if not content.strip():
        return []

    docs = splitter.create_documents([content])
    
    chunks: List[dict] = []
    for idx, doc in enumerate(docs):
        start_char = doc.metadata.get("start_index", 0)
        end_char = start_char + len(doc.page_content)
        
        # Convert character offsets to 1-indexed line numbers
        start_line = content.count("\n", 0, start_char) + 1
        end_line = content.count("\n", 0, end_char) + 1

        name = f"chunk-{idx+1}"
        desc = _generate_description(doc.page_content, name, file_path)
        chunks.append(_make_chunk(
            file_path=file_path,
            language=language,
            name=name,
            code_content=doc.page_content,
            start_line=start_line,
            end_line=end_line,
            chunk_type="block",
            description=desc,
        ))

    return chunks


# ── Public API ────────────────────────────────────────────────────────

def chunk_file(content: str, file_path: str, language: str) -> List[dict]:
    """
    Main entry point — chunk a file using the best strategy for its language.

    Returns:
        List of chunk dicts, each with keys "document" and "metadata".
        The "document" value has the context header prepended so ChromaDB
        stores it with the full File/Language/Function context.
    """
    if not content or not content.strip():
        return []

    if language == "python":
        result = _chunk_python(content, file_path)
    else:
        result = _chunk_recursive_langchain(content, file_path, language)

    logger.debug(
        f"chunk_file_done  file={file_path}  language={language}  chunks={len(result)}"
    )
    return result


# ── Backward-compat shim (old callers used CodeChunk dataclass) ────────

class CodeChunk:
    """
    Thin shim for code that still calls chunk_file() and expects a
    CodeChunk-like object. New code should use the dict return directly.
    """
    __slots__ = ("content", "file_path", "start_line", "end_line",
                 "language", "chunk_type", "name", "document")

    def __init__(self, chunk_dict: dict):
        meta             = chunk_dict["metadata"]
        self.document    = chunk_dict["document"]
        self.content     = chunk_dict["document"]          # full doc including header
        self.file_path   = meta["file_path"]
        self.start_line  = meta["start_line"]
        self.end_line    = meta["end_line"]
        self.language    = meta["language"]
        self.chunk_type  = meta["chunk_type"]
        self.name        = meta["chunk_name"]

    @property
    def token_count(self) -> int:
        return int(len(self.content.split()) * 1.3)


def chunk_file_as_objects(content: str, file_path: str, language: str) -> List[CodeChunk]:
    """Return chunks as CodeChunk objects instead of dicts (legacy compat)."""
    return [CodeChunk(c) for c in chunk_file(content, file_path, language)]
